print("welcome to word encrypter")
encrypt = input("Enter the word you want to encrypt: ")
encrypt = encrypt.lower()
encrypt = encrypt.replace("a", "1")
encrypt = encrypt.replace("b", "2") 
encrypt = encrypt.replace("c", "3")
encrypt = encrypt.replace("d", "4")
encrypt = encrypt.replace("e", "5")
encrypt = encrypt.replace("f", "6")
encrypt = encrypt.replace("g", "7")
encrypt = encrypt.replace("h", "8")
encrypt = encrypt.replace("i", "9")
encrypt = encrypt.replace("j", "a")
encrypt = encrypt.replace("k", "b")
encrypt = encrypt.replace("l", "c")
encrypt = encrypt.replace("m", "d")
encrypt = encrypt.replace("n", "e")
encrypt = encrypt.replace("o", "f")
encrypt = encrypt.replace("p", "g")
encrypt = encrypt.replace("q", "h")
encrypt = encrypt.replace("r", "i")
encrypt = encrypt.replace("s", "j")
encrypt = encrypt.replace("t", "k")
encrypt = encrypt.replace("u", ">")
encrypt = encrypt.replace("v", "<")
encrypt = encrypt.replace("w", "|")
encrypt = encrypt.replace("x", "}")
encrypt = encrypt.replace("y", "{")
encrypt = encrypt.replace("z", "/")
print(encrypt)

y=input("welcome to word encrypter, would you like to decrypt the word you just encrypted?, if so type yes or type no to exit: ")
y=y.lower()
if y=="no":
    print("thank you for using the word encrypter")
else:
    encrypt = encrypt.replace("/", "z")
    encrypt = encrypt.replace("{", "y")
    encrypt = encrypt.replace("}", "x")
    encrypt = encrypt.replace("|", "w")
    encrypt = encrypt.replace("<", "v")
    encrypt = encrypt.replace(">", "u")
    encrypt = encrypt.replace("k", "t")
    encrypt = encrypt.replace("j", "s")
    encrypt = encrypt.replace("i", "r")
    encrypt = encrypt.replace("h", "q")
    encrypt = encrypt.replace("g", "p")
    encrypt = encrypt.replace("f", "o")
    encrypt = encrypt.replace("e", "n")
    encrypt = encrypt.replace("d", "m")
    encrypt = encrypt.replace("c", "l")
    encrypt = encrypt.replace("b", "k")
    encrypt = encrypt.replace("a", "j")
    encrypt = encrypt.replace("9", "i")
    encrypt = encrypt.replace("8", "h")
    encrypt = encrypt.replace("7", "g")
    encrypt = encrypt.replace("6", "f")
    encrypt = encrypt.replace("5", "e")
    encrypt = encrypt.replace("4", "d")
    encrypt = encrypt.replace("3", "c")
    encrypt = encrypt.replace("2", "b")
    encrypt = encrypt.replace("1", "a")

    print(encrypt)
    print("thank you for using the word encrypter")
